spring.application.name=akademik-plus


#database
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${POSTGRES_DB:akademik-plus}
spring.datasource.username=${POSTGRES_USER:akademik}
spring.datasource.password=${POSTGRES_PASSWORD:akademik_pass}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#stripe
stripe.secret.key=${STRIPE_SECRET_KEY}

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.docExpansion=full

#JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION}

#Mail (configure SMTP to enable email sending)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply@akademik-plus.com

#File upload
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#Default admin (created on first startup if no admin exists)
app.admin.email=${ADMIN_EMAIL:admin@akademik-plus.com}
app.admin.password=${ADMIN_PASSWORD:Admin1234!}